### ISSUE TITLE
document drivers original versions

### ISSUE THREAD

**Issue by netzulo** [netzulo/qadrivers#3]
# Reported by

@jburns24

# TODOs

- [x] what **chromedriver** are using ? **v2.33**
- [x] what **firefoxdriver** are using ? **v0.19.0**
- [x] what **phantomjsdriver** are using ? **v2.1.1**
- [x] what **internetexplorerdriver** are using ? **v3.5.3**
- [x] what **edgedriver** are using ? **v5.16299**
- [x] what **operadriver** are using ? **v2.32**

**Comment by jburns24** [comment]
Not sure if this question is directed at me but if so my org only tests on chrome, firefox, and IE (edge will be coming) but my drivers versions are
chromedriver 2.33.0
geckodriver (firefoxdriver) 0.19.1
iedriver 3.7

**Comment by netzulo** [comment]
no problem, im fixing this, give some minutes :)

**Comment by netzulo** [comment]
@jburns24  DONE!  now im going to FIX qalab to get more easily tests reports for your issue on selenium
